import {NextResponse} from 'next/server';
import {readDB,writeDB,Item,nextId,itemStatus,audit,auditChange} from '@/lib/db';
import {can,requireUser} from '@/lib/auth';
const s=(v:unknown)=>String(v??'').trim(); const num=(v:unknown)=>Number(v);
function prices(b:any){return {buyPrice:num(b.buyPrice),sellPrice:num(b.sellPrice??b.unitPrice)}}
function validPrices(p:any){return Number.isFinite(p.buyPrice)&&p.buyPrice>=0&&Number.isFinite(p.sellPrice)&&p.sellPrice>=0}
export async function POST(req:Request){try{const user=await requireUser();if(!can(user,'createItem'))return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json();const db=readDB();const p=prices(b);const item:Item={id:nextId('SKU',db.items),name:s(b.name),category:s(b.category),itemType:s(b.itemType)||'General',measurementUnit:s(b.measurementUnit)||'Piece',storeId:s(b.storeId),quantity:num(b.quantity),minThreshold:num(b.minThreshold),buyPrice:p.buyPrice,sellPrice:p.sellPrice,unitPrice:p.sellPrice,barcode:s(b.barcode)||`890${Date.now()}${Math.floor(Math.random()*100)}`,createdAt:new Date().toISOString(),status:'ACTIVE'};if(!item.name||!db.stores.some(x=>x.id===item.storeId)||!Number.isInteger(item.quantity)||item.quantity<0||!Number.isFinite(item.minThreshold)||item.minThreshold<0||!validPrices(p))return NextResponse.json({error:'Invalid item data. Buy and sell prices must be non-negative numbers.'},{status:400});if(db.items.some(x=>x.barcode===item.barcode))return NextResponse.json({error:'Barcode already exists'},{status:409});db.items.unshift(item);audit(db,'CREATE','ITEM',item.id,user.name,`Created ${item.name}`);writeDB(db);return NextResponse.json({...item,status:itemStatus(item)},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='UNAUTHORIZED'?'Unauthorized':'Request failed'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500});}}
export async function PATCH(req:Request){try{const user=await requireUser();const b=await req.json();const db=readDB();const i=db.items.find(x=>x.id===s(b.id));if(!i)return NextResponse.json({error:'Item not found'},{status:404});
 if(b.status!==undefined){if(!can(user,'deleteItem'))return NextResponse.json({error:'Forbidden'},{status:403});const next=s(b.status).toUpperCase();if(!['ACTIVE','DISABLED'].includes(next))return NextResponse.json({error:'Status must be ACTIVE or DISABLED'},{status:400});if(i.status===next)return NextResponse.json({...i,status:itemStatus(i)});const before={status:i.status||'ACTIVE',disabledAt:i.disabledAt||null,disabledBy:i.disabledByName||null,disabledReason:i.disabledReason||null};i.status=next as 'ACTIVE'|'DISABLED';if(next==='DISABLED'){i.disabledAt=new Date().toISOString();i.disabledById=user.id;i.disabledByName=user.name;i.disabledReason=s(b.reason)||'Disabled by authorised user';}else{delete i.disabledAt;delete i.disabledById;delete i.disabledByName;delete i.disabledReason;}auditChange(db,next==='DISABLED'?'DISABLE':'ENABLE','ITEM',i.id,user.name,`${next==='DISABLED'?'Disabled':'Enabled'} ${i.name}`,before,{status:i.status,disabledAt:i.disabledAt||null,disabledBy:i.disabledByName||null,disabledReason:i.disabledReason||null});writeDB(db);return NextResponse.json({...i,status:itemStatus(i)});}
 if(!can(user,'editItem'))return NextResponse.json({error:'Forbidden'},{status:403});const p=prices(b),name=s(b.name),category=s(b.category),itemType=s(b.itemType)||'General',measurementUnit=s(b.measurementUnit)||'Piece',storeId=s(b.storeId),minThreshold=num(b.minThreshold);if(!name||!db.stores.some(x=>x.id===storeId)||!Number.isFinite(minThreshold)||minThreshold<0||!validPrices(p))return NextResponse.json({error:'Invalid item data. Buy and sell prices must be non-negative numbers.'},{status:400});const before={name:i.name,category:i.category,itemType:i.itemType,measurementUnit:i.measurementUnit,storeId:i.storeId,minThreshold:i.minThreshold,buyPrice:i.buyPrice,sellPrice:i.sellPrice,status:i.status||'ACTIVE'};Object.assign(i,{name,category,itemType,measurementUnit,storeId,minThreshold,buyPrice:p.buyPrice,sellPrice:p.sellPrice,unitPrice:p.sellPrice});auditChange(db,'UPDATE','ITEM',i.id,user.name,`Updated ${i.name}`,before,{name:i.name,category:i.category,itemType:i.itemType,measurementUnit:i.measurementUnit,storeId:i.storeId,minThreshold:i.minThreshold,buyPrice:i.buyPrice,sellPrice:i.sellPrice,status:i.status||'ACTIVE'});writeDB(db);return NextResponse.json({...i,status:itemStatus(i)});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='UNAUTHORIZED'?'Unauthorized':'Request failed'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500});}}

export async function DELETE(req:Request){try{const user=await requireUser();if(!can(user,'deleteItem'))return NextResponse.json({error:'Forbidden'},{status:403});const {id}=await req.json();const db=readDB();const i=db.items.find(x=>x.id===s(id));if(!i)return NextResponse.json({error:'Item not found'},{status:404});if(db.transactions.some(t=>t.itemId===i.id))return NextResponse.json({error:'Cannot permanently delete an item with transaction history. Disable it instead.'},{status:409});db.items=db.items.filter(x=>x.id!==i.id);audit(db,'DELETE','ITEM',i.id,user.name,`Permanently deleted ${i.name}`,[{field:'status',before:i.status||'ACTIVE',after:'DELETED'}]);writeDB(db);return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='UNAUTHORIZED'?'Unauthorized':'Request failed'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500});}}
