import {NextResponse} from 'next/server';
import {readDB,writeDB,nextId,audit,taxCalculation} from '@/lib/db';
import {can,requireUser} from '@/lib/auth';
const text=(v:unknown)=>String(v??'').trim();
function fail(e:unknown){const unauthorized=e instanceof Error&&e.message==='UNAUTHORIZED';return NextResponse.json({error:unauthorized?'Unauthorized':'Request failed'},{status:unauthorized?401:500});}
export async function POST(req:Request){try{
 const user=await requireUser(); if(!can(user,'generateProforma'))return NextResponse.json({error:'Forbidden'},{status:403});
 const body=await req.json(); const customerName=text(body.customerName),storeId=text(body.storeId),reference=text(body.reference),note=text(body.note); const lines=Array.isArray(body.lines)?body.lines:[]; const taxInclusive=body.taxInclusive===true; const db=readDB(); const configuredTaxRate=Number(db.settings?.taxRate); const taxRate=configuredTaxRate; if(!Number.isFinite(taxRate)||taxRate<0||taxRate>100)return NextResponse.json({error:'Tax rate must be between 0 and 100 percent'},{status:400});
 if(!customerName)return NextResponse.json({error:'Customer / organization is required'},{status:400});
 if(!storeId||!db.stores.some(s=>s.id===storeId))return NextResponse.json({error:'Select a valid store'},{status:400});
 if(!lines.length||lines.length>100)return NextResponse.json({error:'Add between 1 and 100 proforma lines'},{status:400});
 const seen=new Set<string>(); const normalized=[] as any[]; let subtotal=0;
 for(const l of lines){const item=db.items.find(i=>i.id===text(l.itemId));const qty=Number(l.qty),unitPrice=Number(l.unitPrice);if(!item)return NextResponse.json({error:'An item on this proforma was not found'},{status:404});if(item.status==='DISABLED')return NextResponse.json({error:`Item ${item.name} is disabled and cannot be used.`},{status:409});if(item.storeId!==storeId)return NextResponse.json({error:'All proforma items must belong to the selected store'},{status:400});if(seen.has(item.id))return NextResponse.json({error:'Each item may appear only once'},{status:400});seen.add(item.id);if(!Number.isInteger(qty)||qty<=0||!Number.isFinite(unitPrice)||unitPrice<0)return NextResponse.json({error:'Quantities must be positive whole numbers and prices must be valid'},{status:400});const amount=qty*unitPrice;subtotal+=amount;normalized.push({itemId:item.id,itemName:item.name,sku:item.id,unit:item.measurementUnit||'Piece',qty,unitPrice,amount});}
 const calculated=taxCalculation(subtotal,taxRate,taxInclusive); const taxAmount=calculated.taxAmount; const total=calculated.total; const id=nextId('PF',db.proformas);const p={id,number:id,customerName,customerPhone:text(body.customerPhone)||undefined,storeId,userId:user.id,userName:user.name,timestamp:new Date().toISOString(),status:'DRAFT' as const,lines:normalized,subtotal,taxRate,taxAmount,total,taxInclusive,reference:reference||undefined,note:note||undefined};db.proformas.unshift(p);audit(db,'CREATE','PROFORMA',id,user.name,`Created proforma ${id} for ${customerName}; no stock changed`);writeDB(db);return NextResponse.json({proforma:p});
 }catch(e){return fail(e)}}
export async function PATCH(req:Request){try{
 const user=await requireUser();if(!can(user,'validateProforma'))return NextResponse.json({error:'Forbidden'},{status:403});
 if(!user.receiptSignature)return NextResponse.json({error:'Upload your authorization signature in Settings before validating a proforma.'},{status:400});
 const body=await req.json();const id=text(body.id);const db=readDB();const p=db.proformas.find(x=>x.id===id);if(!p)return NextResponse.json({error:'Proforma not found'},{status:404});if(p.status==='VALIDATED')return NextResponse.json({error:`Already validated and converted to receipt ${p.receiptId||''}`},{status:409});
 for(const line of p.lines){const item=db.items.find(i=>i.id===line.itemId);if(!item||item.storeId!==p.storeId)return NextResponse.json({error:`Item ${line.itemName} is no longer available in the selected store`},{status:409});if(item.quantity<line.qty)return NextResponse.json({error:`Insufficient stock for ${item.name}: requested ${line.qty}, available ${item.quantity}`},{status:409});}
 const now=new Date().toISOString(),receiptId=nextId('RCT',db.receipts),transactions:any[]=[];let totalSales=0,totalCost=0;const subtotal=Number(p.subtotal??p.total??0); const taxRate=Number(db.settings?.taxRate); if(!Number.isFinite(taxRate)||taxRate<0||taxRate>100)return NextResponse.json({error:'Tax rate is not configured. Set it in Settings before validating this proforma.'},{status:400}); const taxInclusive=p.taxInclusive===true; const calculated=taxCalculation(subtotal,taxRate,taxInclusive); p.taxRate=calculated.taxRate; p.taxAmount=calculated.taxAmount; p.total=calculated.total; const grossMultiplier=subtotal>0?Number(calculated.total||0)/subtotal:1;
 for(const line of p.lines){const item=db.items.find(i=>i.id===line.itemId)!;const buyPrice=Number(item.buyPrice||0);item.quantity-=line.qty;const grossLineAmount=line.amount*grossMultiplier; const grossUnitPrice=line.unitPrice*grossMultiplier; const tx:any={id:nextId('TRX',db.transactions),itemId:item.id,type:'OUT',qty:line.qty,user:user.name,userId:user.id,storeId:item.storeId,timestamp:now,note:p.note||`Validated proforma ${p.number}`,recipient:p.customerName,customerPhone:p.customerPhone,reference:p.reference||p.number,buyPrice,sellPrice:grossUnitPrice,unitPrice:grossUnitPrice,totalValue:grossLineAmount,costValue:line.qty*buyPrice,profit:grossLineAmount-line.qty*buyPrice,receiptId};db.transactions.unshift(tx);transactions.push(tx);totalSales+=tx.totalValue;totalCost+=tx.costValue;}
 const receipt:any={id:receiptId,number:receiptId,customerName:p.customerName,customerPhone:p.customerPhone,storeId:p.storeId,userId:user.id,userName:user.name,timestamp:now,reference:p.reference||p.number,note:p.note,subtotal,taxRate:calculated.taxRate,taxAmount:calculated.taxAmount,taxInclusive,totalSales:calculated.total,totalCost,profit:calculated.total-totalCost,transactionIds:transactions.map(t=>t.id),authorizerSignature:user.receiptSignature,authorizerName:user.name,proformaId:p.id};db.receipts.unshift(receipt);p.status='VALIDATED';p.validatedAt=now;p.validatedById=user.id;p.validatedByName=user.name;p.validatedBySignature=user.receiptSignature;p.receiptId=receiptId;audit(db,'VALIDATE','PROFORMA',p.id,user.name,`Validated proforma ${p.number}; generated receipt ${receiptId} and deducted stock`,[{field:'status',before:'DRAFT',after:'VALIDATED'},{field:'receiptId',before:null,after:receiptId},{field:'validatedBy',before:null,after:user.name}]);writeDB(db);return NextResponse.json({proforma:p,receipt:`/receipts/${receiptId}`,receiptId});
 }catch(e){return fail(e)}}
