import {NextResponse} from 'next/server';
import {readDB,writeDB,nextId,audit,auditChange,taxCalculation} from '@/lib/db';
import {can,requireUser} from '@/lib/auth';
const text=(v:unknown)=>String(v??'').trim();
export async function POST(req:Request){try{
 const user=await requireUser(); if(!can(user,'generateReceipt'))return NextResponse.json({error:'Forbidden'},{status:403});
 const body=await req.json(); const customerName=text(body.customerName||body.recipient); const customerPhone=text(body.customerPhone); const reference=text(body.reference),note=text(body.note); const lines=Array.isArray(body.lines)?body.lines:[];
 if(!customerName)return NextResponse.json({error:'Customer name is required'},{status:400});
 if(customerPhone && !/^[0-9+() .-]{6,25}$/.test(customerPhone))return NextResponse.json({error:'Enter a valid customer phone number or leave it blank'},{status:400});
 if(!lines.length)return NextResponse.json({error:'Add at least one item to the receipt list'},{status:400}); if(lines.length>100)return NextResponse.json({error:'A receipt cannot contain more than 100 lines'},{status:400});
 const db=readDB(); const taxInclusive=body.taxInclusive===true; const taxRate=Number(db.settings?.taxRate); if(!Number.isFinite(taxRate)||taxRate<0||taxRate>100)return NextResponse.json({error:'Tax rate must be between 0 and 100 percent'},{status:400}); const normalized=lines.map((line:any)=>({itemId:text(line.itemId),qty:Number(line.qty),sellPrice:Number(line.sellPrice??line.amount)})); const seen=new Set<string>();
 let receiptStoreId='';
 for(const line of normalized){const item=db.items.find(i=>i.id===line.itemId); if(!line.itemId||seen.has(line.itemId))return NextResponse.json({error:'Each item can appear only once on a receipt'},{status:400});seen.add(line.itemId); if(!item)return NextResponse.json({error:`Item not found: ${line.itemId}`},{status:404}); if(!receiptStoreId)receiptStoreId=item.storeId; if(item.storeId!==receiptStoreId)return NextResponse.json({error:'All items on a receipt must belong to the same store.'},{status:400}); if(!Number.isInteger(line.qty)||line.qty<=0)return NextResponse.json({error:`Quantity for ${item.name} must be a whole number greater than 0`},{status:400}); if(line.qty>item.quantity)return NextResponse.json({error:`Insufficient stock for ${item.name}. You requested ${line.qty}, but only ${item.quantity} ${item.quantity===1?'unit':'units'} are available.`},{status:409}); if(!Number.isFinite(line.sellPrice)||line.sellPrice<0)return NextResponse.json({error:`Enter a valid selling price for ${item.name}`},{status:400}); }
 const receiptId=nextId('RCT',db.receipts); const now=new Date().toISOString(); const transactions:any[]=[]; const subtotal=normalized.reduce((n,l)=>n+Number(l.qty||0)*Number(l.sellPrice||0),0); const calculated=taxCalculation(subtotal,taxRate,taxInclusive); const grossMultiplier=subtotal>0?calculated.total/subtotal:1; let totalCost=0;
 for(const line of normalized){const item=db.items.find(i=>i.id===line.itemId)!; const buyPrice=Number(item.buyPrice??0), sale=line.sellPrice, grossSale=sale*grossMultiplier; const previousQuantity=item.quantity; item.quantity-=line.qty; const tx:any={id:nextId('TRX',db.transactions),itemId:item.id,type:'OUT',qty:line.qty,user:user.name,userId:user.id,storeId:item.storeId,timestamp:now,note,recipient:customerName,customerPhone:customerPhone||undefined,reference,buyPrice,sellPrice:grossSale,unitPrice:grossSale,totalValue:line.qty*grossSale,costValue:line.qty*buyPrice,profit:line.qty*(grossSale-buyPrice),receiptId}; db.transactions.unshift(tx);transactions.push(tx);totalCost+=tx.costValue; auditChange(db,'RECEIPT_ISSUE','ITEM',item.id,user.name,`Receipt ${receiptId}: OUT ${line.qty} ${item.name} for ${customerName}`,{quantity:previousQuantity},{quantity:item.quantity,receiptId}); }
 const receipt={id:receiptId,number:receiptId,customerName,customerPhone:customerPhone||undefined,storeId:transactions[0].storeId,userId:user.id,userName:user.name,timestamp:now,reference:reference||undefined,note:note||undefined,subtotal:calculated.subtotal,taxRate:calculated.taxRate,taxAmount:calculated.taxAmount,taxInclusive,totalSales:calculated.total,totalCost,profit:calculated.total-totalCost,transactionIds:transactions.map(t=>t.id),authorizerSignature:user.receiptSignature||undefined,authorizerName:user.name}; db.receipts.unshift(receipt); writeDB(db);
 return NextResponse.json({receiptId,receipt:`/receipts/${receiptId}`,transactions,totalValue:receipt.totalSales,subtotal:receipt.subtotal,taxRate:receipt.taxRate,taxAmount:receipt.taxAmount,taxInclusive:receipt.taxInclusive,profit:receipt.profit});
}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='UNAUTHORIZED'?'Unauthorized':'Request failed'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500});}}
